@startuml

class Main {
 Interface();
}

class UI {

}

class Player {

}

class Team {

}

class Admin {

}

class Knockout {


}

class GroupStage {

}

class Tournament {

}

class Interface {

}




@enduml