@startuml
!pragma layout smetana

class Main {
 Interface();
}

class UI {
- ArrayList<Team> teamList;

}

class Player {
- String name;
+ Player(String name);
- ArrayList<Player> player
- Scanner sc;
+ String toString();
- createPlayer();

}

class Team {
- int maxAmountOfPlayers;
- int minAmountOfPlayers;
- ArrayList<Team> teamName
- createTeam();
- String team;
+ Team();


}

class Admin {

}

class Knockout {


}


class Tournament {

}

class Interface {

}

Main -- UI
Team --Player : 2.. 5
Main -- Interface
Admin -- Knockout

Admin -- Team

Tournament <|-- Knockout

UI <|-- Player
UI -- Team
UI <|-- Admin


@enduml